name: argox_printer_example
description: Demonstrates how to use the argox_printer plugin.
publish_to: 'none'
environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  argox_printer:
    path: ../
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true