name: argox_printer
description: FFI for Argox Printers using PPLA, PPLB, PPLZ
version: 0.0.9
repository: https://github.com/saviobatista/argox_printer
issue_tracker: https://github.com/saviobatista/argox_printer/issues
documentation: https://github.com/saviobatista/argox_printer/blob/main/DOCUMENTATION.md
environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.3
flutter:
  assets:
    - windows/WinPort.dll
    - windows/Winppla.dll
    - windows/Winpplb.dll
    - windows/Winpplz.dll
platforms:
  windows:
ffigen:
  output: 'lib/src/printer_drivers.dart'
  llvm-path:
    - '/usr/local/opt/llvm'
  headers:
    entry-points:
      - 'windows/ppla.h'
      - 'windows/pplb.h'
      - 'windows/pplz.h'