name: argox_printer
description: FFI for Argox Printers using PPLA, PPLB, PPLZ
version: 0.0.3
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
    - assets/WinPort.dll
    - assets/Winppla.dll
    - assets/Winpplb.dll
    - assets/Winpplz.dll