name: Dart CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .
    
    - name: Analyze project source
      run: dart analyze
    
    - name: Run tests
      run: dart test
    
    - name: Run tests with coverage
      run: dart test --coverage=coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info
        fail_ci_if_error: false

  example_test:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd example
        flutter pub get
    
    - name: Analyze example
      run: |
        cd example
        flutter analyze
    
    - name: Run example tests
      run: |
        cd example
        flutter test

  windows_test:
    runs-on: windows-latest
    needs: test

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        cd example
        flutter pub get
    
    - name: Build Windows example
      run: |
        cd example
        flutter build windows --no-tree-shake-icons
      continue-on-error: true  # Windows build might fail without printer hardware 